In [3]:
from google.colab import drive
drive.mount('/content/drive')

!pip install pandas

Mounted at /content/drive
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd
import re
import os

In [5]:
input_path = '/content/drive/MyDrive/semester 6/Penalaran Komputer/UAS/CSV/putusan_ma__2025-06-23.csv'
df = pd.read_csv(input_path)
df.head()

,judul,nomor,tingkat_proses,klasifikasi,kata_kunci,tahun,tanggal_register,lembaga_peradilan,jenis_lembaga_peradilan,hakim_ketua,...,catatan_amar,tanggal_musyawarah,tanggal_dibacakan,kaidah,status,abstrak,link,link_pdf,file_name_pdf,text_pdf
0,Putusan PN PALU Nomor 116/Pid.B/2025/PN Pal Ta...,Putusan PN PALU Nomor 116/Pid.B/2025/PN Pal Ta...,Pertama,Pidana Umum \n Pidana Umum Pembunuhan,Pembunuhan,2025,28 April 2025,PN PALU,PN,Hakim Ketua Dwi Hatmodjo,...,MENGADILI:1. Menyatakan Terdakwa Moh. Zakir A...,19 Juni 2025,19 Juni 2025,—,NaN,NaN,https://putusan3.mahkamahagung.go.id/direktori...,https://putusan3.mahkamahagung.go.id/direktori...,zaf04da6b90c725a80d6313431383131,Direktori Putusan Mahkamah Agung Republik Indo...
1,Putusan PN TUAL Nomor 10/Pid.B/2025/PN Tul Tan...,Putusan PN TUAL Nomor 10/Pid.B/2025/PN Tul Tan...,Pertama,Pidana Umum Pembunuhan,NaN,2025,18 Februari 2025,PN TUAL,PN,Jeffry Pratama,...,MENGADILI:1. Menyatakan Terdakwa Yesayas Heatu...,16 Mei 2025,19 Mei 2025,—,NaN,NaN,https://putusan3.mahkamahagung.go.id/direktori...,https://putusan3.mahkamahagung.go.id/direktori...,zaf041d316f30d32b48b313330353332,Direktori Putusan Mahkamah Agung Republik Indo...
2,Putusan PN KAYUAGUNG Nomor 97/Pid.B/2025/PN Ka...,Putusan PN KAYUAGUNG Nomor 97/Pid.B/2025/PN Ka...,Pertama,Pidana Umum \n Pidana Umum Pembunuhan,Pembunuhan,2025,10 Maret 2025,PN KAYUAGUNG,PN,Hakim Ketua Anisa Lestari,...,MENGADILI: Menyatakan Terdakwa FAUZAN ROHMAT B...,22 Mei 2025,22 Mei 2025,—,NaN,NaN,https://putusan3.mahkamahagung.go.id/direktori...,https://putusan3.mahkamahagung.go.id/direktori...,zaf036e9bfcb8ea6ba5b313535303032,Direktori Putusan Mahkamah Agung Republik Indo...
3,Putusan PN Cikarang Nomor 10/Pid.B/2025/PN Ckr...,Putusan PN Cikarang Nomor 10/Pid.B/2025/PN Ckr...,Pertama,Pidana Umum \n Pidana Umum Pembunuhan,Pembunuhan,2025,16 Januari 2025,PN Cikarang,PN,Hakim Ketua Isnandar S. Nasution,...,MENGADILI: 1. Menyatakan Terdakwa HAGISTIKO PR...,4 Juni 2025,4 Juni 2025,—,NaN,NaN,https://putusan3.mahkamahagung.go.id/direktori...,https://putusan3.mahkamahagung.go.id/direktori...,zaf04b1a394e977a8f8f303832373235,Direktori Putusan Mahkamah Agung Republik Indo...
4,Putusan PN NABIRE Nomor 23/Pid.B/2025/PN Nab T...,Putusan PN NABIRE Nomor 23/Pid.B/2025/PN Nab T...,Pertama,Pidana Umum \n Pidana Umum Pembunuhan,Pembunuhan,2025,13 Maret 2025,PN NABIRE,PN,Hakim Ketua Yanuar Nurul Fahmi,...,MENETAPKAN:1.Menyatakan Penununtutan Jaksa Pen...,19 Juni 2025,19 Juni 2025,—,NaN,NaN,https://putusan3.mahkamahagung.go.id/direktori...,https://putusan3.mahkamahagung.go.id/direktori...,zaf04da896f96040bae4313433313333,Direktori Putusan Mahkamah Agung Republik Indo...

In [6]:
# Cek dan hapus duplikat berdasarkan nomor perkara (jika ada)
print("Jumlah awal:", len(df))
df = df.drop_duplicates(subset=['nomor'])
print("Jumlah setelah hapus duplikat berdasarkan nomor:", len(df))

Jumlah awal: 359
Jumlah setelah hapus duplikat berdasarkan nomor: 344

In [7]:
df = df[df['kata_kunci'].str.contains("pembunuhan", case=False, na=False)].copy()
print("Jumlah kasus pembunuhan:", len(df))
df.head()

Jumlah kasus pembunuhan: 309

,judul,nomor,tingkat_proses,klasifikasi,kata_kunci,tahun,tanggal_register,lembaga_peradilan,jenis_lembaga_peradilan,hakim_ketua,...,catatan_amar,tanggal_musyawarah,tanggal_dibacakan,kaidah,status,abstrak,link,link_pdf,file_name_pdf,text_pdf
0,Putusan PN PALU Nomor 116/Pid.B/2025/PN Pal Ta...,Putusan PN PALU Nomor 116/Pid.B/2025/PN Pal Ta...,Pertama,Pidana Umum \n Pidana Umum Pembunuhan,Pembunuhan,2025,28 April 2025,PN PALU,PN,Hakim Ketua Dwi Hatmodjo,...,MENGADILI:1. Menyatakan Terdakwa Moh. Zakir A...,19 Juni 2025,19 Juni 2025,—,NaN,NaN,https://putusan3.mahkamahagung.go.id/direktori...,https://putusan3.mahkamahagung.go.id/direktori...,zaf04da6b90c725a80d6313431383131,Direktori Putusan Mahkamah Agung Republik Indo...
2,Putusan PN KAYUAGUNG Nomor 97/Pid.B/2025/PN Ka...,Putusan PN KAYUAGUNG Nomor 97/Pid.B/2025/PN Ka...,Pertama,Pidana Umum \n Pidana Umum Pembunuhan,Pembunuhan,2025,10 Maret 2025,PN KAYUAGUNG,PN,Hakim Ketua Anisa Lestari,...,MENGADILI: Menyatakan Terdakwa FAUZAN ROHMAT B...,22 Mei 2025,22 Mei 2025,—,NaN,NaN,https://putusan3.mahkamahagung.go.id/direktori...,https://putusan3.mahkamahagung.go.id/direktori...,zaf036e9bfcb8ea6ba5b313535303032,Direktori Putusan Mahkamah Agung Republik Indo...
3,Putusan PN Cikarang Nomor 10/Pid.B/2025/PN Ckr...,Putusan PN Cikarang Nomor 10/Pid.B/2025/PN Ckr...,Pertama,Pidana Umum \n Pidana Umum Pembunuhan,Pembunuhan,2025,16 Januari 2025,PN Cikarang,PN,Hakim Ketua Isnandar S. Nasution,...,MENGADILI: 1. Menyatakan Terdakwa HAGISTIKO PR...,4 Juni 2025,4 Juni 2025,—,NaN,NaN,https://putusan3.mahkamahagung.go.id/direktori...,https://putusan3.mahkamahagung.go.id/direktori...,zaf04b1a394e977a8f8f303832373235,Direktori Putusan Mahkamah Agung Republik Indo...
4,Putusan PN NABIRE Nomor 23/Pid.B/2025/PN Nab T...,Putusan PN NABIRE Nomor 23/Pid.B/2025/PN Nab T...,Pertama,Pidana Umum \n Pidana Umum Pembunuhan,Pembunuhan,2025,13 Maret 2025,PN NABIRE,PN,Hakim Ketua Yanuar Nurul Fahmi,...,MENETAPKAN:1.Menyatakan Penununtutan Jaksa Pen...,19 Juni 2025,19 Juni 2025,—,NaN,NaN,https://putusan3.mahkamahagung.go.id/direktori...,https://putusan3.mahkamahagung.go.id/direktori...,zaf04da896f96040bae4313433313333,Direktori Putusan Mahkamah Agung Republik Indo...
5,Putusan PN PALANGKARAYA Nomor 50/Pid.B/2025/PN...,Putusan PN PALANGKARAYA Nomor 50/Pid.B/2025/PN...,Pertama,Pidana Umum \n Pidana Umum Pembunuhan,Pembunuhan,2025,27 Februari 2025,PN PALANGKARAYA,PN,Hakim Ketua Muhammad Ramdes,...,MENGADILI: Menyatakan Terdakwa Muhammad Haryon...,19 Mei 2025,19 Mei 2025,—,NaN,NaN,https://putusan3.mahkamahagung.go.id/direktori...,https://putusan3.mahkamahagung.go.id/direktori...,zaf035ddada4792ab8b7303735313036,Direktori Putusan Mahkamah Agung Republik Indo...

In [8]:
df['case_id'] = ['case_{:03d}'.format(i+1) for i in range(len(df))]

In [9]:
def get_summary(text, n=3):
    if pd.isna(text):
        return ""
    sentences = re.split(r'(?<=[.!?]) +', text.strip())
    return ' '.join(sentences[:n])

df['ringkasan_fakta'] = df['text_pdf'].apply(lambda x: get_summary(x, n=3))

In [10]:
def extract_pasal(text):
    if pd.isna(text):
        return ""
    match = re.findall(r'Pasal\s\d+[A-Za-z\s]*', text)
    return '; '.join(set(match)) if match else ""

df['pasal'] = df['text_pdf'].apply(extract_pasal)

In [11]:
df['text_full'] = df['text_pdf']

In [12]:
selected_cols = ['case_id', 'nomor', 'tanggal_register', 'tanggal_dibacakan', 'ringkasan_fakta', 'pasal', 'amar','catatan_amar', 'text_full']
df_out = df[selected_cols]
df_out.head()

,case_id,nomor,tanggal_register,tanggal_dibacakan,ringkasan_fakta,pasal,amar,catatan_amar,text_full
0,case_001,Putusan PN PALU Nomor 116/Pid.B/2025/PN Pal Ta...,28 April 2025,19 Juni 2025,Direktori Putusan Mahkamah Agung Republik Indo...,Pasal 338 KUHP Jo Pasal ; Pasal 65 ayat ; Pasa...,Lain-lain,MENGADILI:1. Menyatakan Terdakwa Moh. Zakir A...,Direktori Putusan Mahkamah Agung Republik Indo...
2,case_002,Putusan PN KAYUAGUNG Nomor 97/Pid.B/2025/PN Ka...,10 Maret 2025,22 Mei 2025,Direktori Putusan Mahkamah Agung Republik Indo...,Pasal 222 Undang; Pasal 8 ayat ; Pasal 187 Und...,Lain-lain,MENGADILI: Menyatakan Terdakwa FAUZAN ROHMAT B...,Direktori Putusan Mahkamah Agung Republik Indo...
3,case_003,Putusan PN Cikarang Nomor 10/Pid.B/2025/PN Ckr...,16 Januari 2025,4 Juni 2025,Direktori Putusan Mahkamah Agung Republik Indo...,Pasal 10 KUHP bahwa pembebanan biaya perkara k...,Lain-lain,MENGADILI: 1. Menyatakan Terdakwa HAGISTIKO PR...,Direktori Putusan Mahkamah Agung Republik Indo...
4,case_004,Putusan PN NABIRE Nomor 23/Pid.B/2025/PN Nab T...,13 Maret 2025,19 Juni 2025,Direktori Putusan Mahkamah Agung Republik Indo...,,Lain-lain,MENETAPKAN:1.Menyatakan Penununtutan Jaksa Pen...,Direktori Putusan Mahkamah Agung Republik Indo...
5,case_005,Putusan PN PALANGKARAYA Nomor 50/Pid.B/2025/PN...,27 Februari 2025,19 Mei 2025,Direktori Putusan Mahkamah Agung Republik Indo...,Pasal 84 ayat ; Pasal 28 ayat ; Pasal 6 ayat ;...,Lain-lain,MENGADILI: Menyatakan Terdakwa Muhammad Haryon...,Direktori Putusan Mahkamah Agung Republik Indo...

In [13]:
output_path = '/content/drive/MyDrive/semester 6/Penalaran Komputer/UAS/processed/cases.csv'
os.makedirs(os.path.dirname(output_path), exist_ok=True)
df_out.to_csv(output_path, index=False)
print("✅ File berhasil disimpan di:", output_path)

✅ File berhasil disimpan di: /content/drive/MyDrive/semester 6/Penalaran Komputer/UAS/processed/cases.csv